### ISSUE TITLE
Markdown support possible?

### ISSUE THREAD

**Issue by krash84** [JonathanWilbur/asn1-ts#1]
It would be nice to see the asn.1 syntax support in VScode's markdown:

Something like in (*.md file):
```
```asn.1
id-ct-TSTInfo  OBJECT IDENTIFIER ::= {
    iso(1) member-body(2) us(840) rsadsi(113549) pkcs(1) pkcs-9(9) smime(16) ct(1) 4
}```
```

**Comment by JonathanWilbur** [comment]
I think I mistakenly directed you to report this issue on the wrong GitHub repo, but no problem. I agree--that would be a cool feature--and one that I thought already worked out-of-the-box when I published my extension. I will get to this, but I will paste this here for now for my reference on how to implement this:

https://github.com/mjbvz/vscode-fenced-code-block-grammar-injection-example

**Comment by JonathanWilbur** [comment]
This has been added in the latest version of the ASN.1 extension, which is version 0.5.0. Enjoy!
