### ISSUE TITLE
Broken toString and toJSON function on 7.0.6

### ISSUE THREAD

**Issue by dicksonhk** [JonathanWilbur/asn1-ts#22]
* **Version**: [`7.0.6`](https://github.com/JonathanWilbur/asn1-ts/commit/17581d844fa5707e6f0f6b61b81d37f2631b6a68#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519)
* **Platform**: N/A
* **Subsystem**: N/A

Calling `toString` and `toJSON` on a `SET_OF` `ASN1Element` that is not uniquely tagged throws `ASN1ConstructionError`, after the introduction of uniqueness checking for `SET` introduced in `v7.0.6`.

Calling `setOf`~~, instead of `set`,~~ could be one way of solving the issue, as both `SET` and `SET_OF` have the same signature.

`source/codecs/ber.ts`, `source/codecs/cer.ts`, `source/codecs/der.ts`:
```typescript
get set (): SET<ASN1Element> {
    const ret = this.sequence;
    if (!isUniquelyTagged(ret)) {
        throw new errors.ASN1ConstructionError("Duplicate tag in SET.", this);
    }
    return ret;
}
```

`source/asn1.ts`
```typescript
// toString()
switch (this.tagNumber) {
    case (ASN1UniversalType.set): return ("{ " + this.set // <-- this could be a SET_OF, with might not be uniquely tagged
        .map((el) => (el.name.length ? `${el.name} ${el.toString()}` : el.toString()))
        .join(" , ") + " }");
}
```

`source/asn1.ts`
```typescript
// toJSON()
switch (this.tagNumber) {
    case (ASN1UniversalType.set): { // <-- this could be a SET_OF, with might not be uniquely tagged
        if (!recurse) {
            return null;
        }
        return this.set.map((el) => el.toJSON());
    }
}
```

**Comment by JonathanWilbur** [comment]
I fixed this just now. I released version 7.0.18, which fixes both this bug and #20 . Thank you so much for your very thoughtful issue reporting and PR!
