### ISSUE TITLE
Library x509-ts do not work in Firefox, Edge or IE

### ISSUE THREAD

**Issue by svkreml** [JonathanWilbur/asn1-ts#6]
1) Create new NG project
2) add _c = Certificate.fromBytes(null);_
3) run
4) _SyntaxError: invalid regexp group_ in browser console, page does not load

https://github.com/svkreml/fireFoxTestX509 project Example
(i add it in src/app/app.component.ts) 

do you have any regexp in lib?

**Comment by JonathanWilbur** [comment]
@svkreml This issue is resolved with version 2.0.0, which is now released. Note that you will have to alter your `package.json` file to update the new major version of `asn1-ts`. I have not updated `x509-ts` with this dependency yet, but I will do so now.

**Comment by JonathanWilbur** [comment]
@svkreml , this is now fixed in the X.509 library as well, in version 0.11.11. Thank you again for reporting this.
