### ISSUE TITLE
Cannot find module '../../../types/External' from 'decodeExternal.js'

### ISSUE THREAD

**Issue by yoursunny** [JonathanWilbur/asn1-ts#7]
* **Version**: 2.8.0
* **Platform**: Ubuntu 18.04, using ext4 filesystem
* **Subsystem**:

[/dist/codecs/x690/decoders/decodeExternal.d.ts](https://unpkg.com/browse/asn1-ts@2.8.0/dist/codecs/x690/decoders/decodeExternal.d.ts) has a reference:

```ts
import External from "../../../types/External";
```

However, [/dist/types](https://unpkg.com/browse/asn1-ts@2.8.0/dist/types/) directory only has an `external.d.ts` file.
On a case sensitive filesystem such as ext4 used on Ubuntu, `external.d.ts` and `External.d.ts` are different files.

This causes [build error](https://travis-ci.com/yoursunny/NDNts/jobs/254899531#L1094):

```
Cannot find module '../../../types/External' from 'decodeExternal.js'
```

It seems that the source file in [/source/types](https://github.com/JonathanWilbur/asn1-ts/tree/6fbe98fdd6a9f279b1c6700b28c3aa5a8421d66a/source/types) is correctly named as `External.ts`.
Therefore, this is a publishing problem. I guess you are building the tarball on a case insensitive filesystem without clearing the cache.
To fix this problem, delete output folder in your clone, and rebuild from a clean clone.

**Comment by JonathanWilbur** [comment]
Sorry about that! I changed the capitalization after initially creating the file. Thanks for reporting this! Version 2.9.1 should be fixed.
